zettel = {
    "arch": {
        "0 Agile architect.md": "# Some really smart words\n![Yes](https://i.imgur.com/sZlktY7.png)\n\n\nShould apply rational thinking at all times [[brain/Brain is the most complex object in known universe.md]]\n\n[[arch/0 Architecture]]",
        "0 Architecture.md": "\"Significant decisions are architecture, and everything else is design\"\n\nComputer architecture, like other architecture, is the art of determining the needs of the business of a structure and then designing to meet those needs as effectively as possible within economic and technological constraints\n\nПо поводу архитектуры - архитектура это всегда наличие ограничений, которые призваны дать какую-то характеристику.\n\n[[arch/0 Agile architect]]",
        "0 Ask whys.md": "### Seek the value in requested capabilities\n\nClients often don't know what they truly want\n\n[[То, чего хотят заказчики, и что им нужно - разные вещи]]\n[[0 Agile architect]]\n[[Ask questions]]\n[[Architect goal]]\n[[Emergent Design]]\n[[Intentional Architecture]]\n[[..\/brain\/Socratic method q and a]]\n[[Understand the problem a tool or idea solves well]]",
        "0 Fast feedback loop PDCA.md": "Plan Do Check Adjust\n\n[[Emergent Design]]\n[[0 Agile architect]]\n[[Architect goal]]\n[[Rewrite twice]]\n[[Missing or changing requirements]]\n[[..\/management\/Фланирование - подход к выполнению проектов]]\n[[..\/management\/Plans vs structure]]\n[[..\/life\/Learning and open mindness]]\n[[..\/management\/Feedback loops should be small]]\n[[..\/management\/Неопределенность нейтральна]]",
        "0 Flexibility.md": "Uncertainty is a key element in the definition of flexibility. Uncertainty can create both risks and opportunities in a system, and it is with the existence of uncertainty that flexibility becomes valuable.\n\n[[Make things non architectural]]\n[[Good arch is thing that enables us to postpone decisions]]\n[[Каскад изменений]]\n[[Intentional Architecture]]\n[[Emergent Design]]\n[[Missing or changing requirements]]\n[[Focus on behavior, not data]]\n[[Complect vs Compose]]\n[[Complexity Unknown unknowns]]\n\nCons:\n[[Making something easy to change contributes to complexity]]\n",
        "0 Information hiding.md": "[[Tell don't ask]]\n[[Hide the complexity]]\n[[True module]]\n[[True invariant]]\n[[True incapsulation]]\n[[Single source of truth]]\n[[Deep modules]]\n[[Каскад изменений]]\n[[Client side call sequence should be owned by the module]]\n[[Autonomous component]]\n[[Focus on behavior, not data]]\n[[We can solve any problem by introducing an extra level of indirection]]\n[[Vertical slices]]\n[[Team first architecture]]\n[[Reverse Conway's maneuver]]\n[[Микросервис - команда]]\n[[Setters can break object invariants]]\n[[Держать связанные данные в одном контексте]]\n[[Не разрезайте монолит по слоям, разрезай по вертикалям (бизнесу)]]",
        "0 Quality attributes.md": "[[0 Flexibility]]\n[[Maintainability]]\n[[Reliability]]\n[[Complexity defined]]\n[[0 Simplicity]]\nTransaction metrics: [[Consistency models]] [[True module]]\n",
        "0 Simplicity.md": "[[Deep modules]]\n[[Cognitive load]]\n[[Для UI, отчетов, view можно реализовывать какие угодно модели]]\n[[Simplicity is about minimizing our dependencies]]\n[[Simple Made Easy]]\n[[Making something easy to change contributes to complexity]]\n[[State is never simple]]\n[[Complexity defined]]\n[[Hide the complexity]]\n[[Single source of truth]]\n[[True invariant]]\n[[True incapsulation]]\n[[Client side call sequence should be owned by the module]]\n[[Tell don't ask]]\n[[Нет проблемы - нет архитектуры]]\n[[Линейное расширение & сквозная ф-ность]]\n\n\n",
        "Architecture jar analogy.md": "If we place several big rocks in a large jar, then add pebbles, and last add sand, we fit them all into our jar. And yes, we could even add water. The point is not that we can always ask the developer to do more! The point is that if we start with the same sand, add the pebbles, and then try to add the big rocks, we cannot fit them all in the jar. To fit them all in, we must start with the big rocks. Architecture is about getting the big rocks in place first. But what are the \"big rocks\"? \nThe architectural elements, the components and their relationships, yes. And architectural mechanisms addressing cross-cutting concerns or systemic properties, yes. Big rocks bear a high cost of change, yes. Is there more?\n\n[[Make things non architectural]]\n[[Intentional Architecture]]\n[[Accidental architecture]]\n",
        "Architecture or design.md": "The distinction is not always clear.\n\n\"Significant decisions are architecture, and everything else is design\"\n\n\"all architecture is design, but not all design is architecture\"\n\n\"A continiuum where coarse-grained is architecture and fine-graned-is design\"\nТак ли это важно? Что дает эта заметка?\n\n[[..\/management\/Plans vs structure]]\n[[..\/management\/Фланирование - подход к выполнению проектов]]\n[[Intentional Architecture]]\n[[Emergent Design]]\n",
        "Aristocracy vs Democracy.md": "Conceptual integrity in turn dictates that the design must proceed from one mind, or from a very small number of agreeing resonant minds.\n\n\"Where architecture tells what happens, implementation tells how it is made to happen.\"[\n\nAre not the architects a new aristocracy, an intellectual elite, set up to tell the poor dumb implementers what to do?\n\nthe answer must be yes and no. Yes, in the sense that there must be few architects, their product must endure longer than that of an implementer, and the architect sits at the focus of forces which he must ultimately resolve in the user's interest. If a system is to have conceptual integrity, someone must control the concepts. That is an aristocracy that needs no apology. No, because the setting of external specifications is not more creative work than the designing of implementations. It is just different creative work. The design of an implementation, given an architecture, requires and allows as much design creativity, as many new ideas, and as much technical brilliance as the design of the external specifications. Indeed, the cost-performance ratio of the product will depend most heavily on the implementer, just as ease of use depends most heavily on the architect.\n\n\/\/ An architect must be on user's side, protecting his interests",
    },
    "brain": {
        "0 Learning.md": "### Learning is making meaningful connections\n\nЕсли нам дать время логически подумать - мы придем к одному. Но бОльшую роль имеют неявные небольшие решения, которые мы принимаем неосознанно в течении дня\n\n\"The one who does the work does the learning\"\n\n[[brain/Brain is the most complex object in known universe]]\n",
        "Brain is the most complex object in known universe.md": "Nothing will make you appreciate human intelligence like learning about how unbelievably challenging it is to try to create a computer as smart as we are. Building skyscrapers, putting humans in space, figuring out the details of how the Big Bang went down—all far easier than understanding our own brain or how to make something as cool as it\n\n\/\/ That's why road from ANI to AGI is so hard\n\/\/ AGI (a computer as smart as humans in general, not just at one narrow specialty\n\n[[brain/0 Learning]]",
        "Change your environment instead of using willpower.md": "When scientists analyze people who appear to have tremendous self-control, it turns out those individuals aren’t all that different from those who are struggling. Instead, “disciplined” people are better at structuring their lives in a way that does not require heroic willpower and self-control.\n\nIn other words, they spend less time in tempting situations. The people with the best self-control are typically the ones who need to use it the least.\n\n\/\/ Once a habit has been encoded, the urge to act follows whenever the environmental cues reappear\nWhen Patty Olwell, a therapist from Austin, Texas, started smoking, she would often light up while riding horses with a friend. Eventually, she quit smoking and avoided it for years. She had also stopped riding. Decades later, she hopped on a horse again and found herself craving a cigarette for the first time in forever. The cues were still internalized; she just hadn’t been exposed to them in a long time.",
    },
    "happiness": {
        "Abundant mediation.md": "Once you are relaxed, picture yourself living in an abundant world. In this abundant world, there are no restraints or limitations. Good things flow past you continuously. Imagine every abundant thing you have ever desired–car, home, friends, love, joy, wealth, success, peace of mind, challenge. Visualize yourself living your life surrounded by this abundance. Repeat this visualization several times a day until it begins to feel real to you. Open your arms, your heart, and your mind. Get out of the way, and let it happen.\n\n[[happiness/Boredom is just an emotion]]",
        "Boredom is just an emotion.md": "It's not an indicator that you're doing something wrong in your life\n\nBefore we had phones and technologies we would just sit around the fire and we would talk and we wouldn't call that boring that was just life\n\nAnd bow we have that endless need for entertainment, anything when nothing is happening we think it's wrong and we need to fix it\n\nNon eventfulness is just a part of our life and you can embrace it as\npeace or you can frantically try to create more chaos\n\n[[happiness/Abundant mediation]]",
    },
}
